export { IAppointment, AppointmentStatus } from './IAppointment'
export { ICalendar } from './ICalendar'
export { ICanceledAppointment } from './ICanceledAppointment'
export { ICategory } from './ICategory'
export { ICount } from './ICount'
export { IDean } from './IDean'
export { IDocument } from './IDocument'
export { IFaculty } from './IFaculty'
export { IPayload } from './IPayload'
export { IPeople } from './IPeople'
export { IReport } from './IReport'
export { IRole } from './IRole'
export { IStatistic } from './IStatistic'
export { IUser } from './IUser'
