export type { ICounts } from './ICounts'
export type { IKeyBool } from './IKeyBool'
export type { IPeopleBase } from './IPeopleBase'
export type { IBase, ICategory, IDocument, IFacultie } from './IResources'
export type { IUserBase } from './IUserBase'
